class MTPOS_Constants:
    ROOT_LOG_FOLDER_ID = "1B2DKW8KSYr3Iu9ZbDE2empDcwhQ3BtTZ"
    SERVICE_NAME = "MTPOS_MATCODE"
    WORKSHEET_TAB_CREDENTIAL="MTPOS_Creds"
    WORKSHEET_TAB_SOR = "MatCode_SOR"
    SEARCH_IN = "All Items"

    MATERIAL_CODE = "Material Code"

    app_type = {"GT", "PD"}

    SUPPLIER = "BAX PHONEKITTING #15010"

